package sector

import "strings"

// OfficialIDXMap maps stock ticker symbols to their official IDX sector categories.
var OfficialIDXMap = map[string]string{
	// Energy
	"AADI": "Energy",
	"ADMR": "Energy",
	"ADRO": "Energy",
	"AKRA": "Energy",
	"BREN": "Energy",
	"BUMI": "Energy",
	"CBRE": "Energy",
	"COAL": "Energy",
	"CUAN": "Energy",
	"DSSA": "Energy",
	"DWGL": "Energy",
	"ELSA": "Energy",
	"ENRG": "Energy",
	"ITMG": "Energy",
	"MEDC": "Energy",
	"PGAS": "Energy",
	"PGEO": "Energy",
	"PTBA": "Energy",
	"PTRO": "Energy",
	"RAJA": "Energy",
	"RATU": "Energy",
	"SINI": "Energy",
	"SULI": "Basic Materials",
	"TCPI": "Infrastructure",

	// Basic Materials
	"AMMN": "Basic Materials",
	"ANTM": "Basic Materials",
	"ARCI": "Basic Materials",
	"AVIA": "Basic Materials",
	"BAJA": "Basic Materials",
	"BRMS": "Basic Materials",
	"BRNA": "Basic Materials",
	"BRPT": "Basic Materials",
	"EKAD": "Basic Materials",
	"EMAS": "Basic Materials",
	"ESSA": "Basic Materials",
	"IFSH": "Basic Materials",
	"IMPC": "Basic Materials",
	"INCF": "Basic Materials",
	"INCO": "Basic Materials",
	"INKP": "Basic Materials",
	"KRAS": "Basic Materials",
	"MBMA": "Basic Materials",
	"MDKA": "Basic Materials",
	"PSAB": "Basic Materials",
	"SMGR": "Basic Materials",
	"TINS": "Basic Materials",
	"TPIA": "Basic Materials",
	"TPL":  "Basic Materials",
	"WTON": "Basic Materials",
	"YPAS": "Basic Materials",

	// Financial Services
	"ADMF": "Financial Services",
	"AHAP": "Financial Services",
	"ARTO": "Financial Services",
	"BANK": "Financial Services",
	"BBCA": "Financial Services",
	"BBHI": "Financial Services",
	"BBNI": "Financial Services",
	"BBRI": "Financial Services",
	"BBSI": "Financial Services",
	"BBTN": "Financial Services",
	"BEKS": "Financial Services",
	"BFIN": "Financial Services",
	"BJBR": "Financial Services",
	"BJTM": "Financial Services",
	"BMAS": "Financial Services",
	"BMRI": "Financial Services",
	"BNGA": "Financial Services",
	"BNII": "Financial Services",
	"BRIS": "Financial Services",
	"MEGA": "Financial Services",
	"SMMA": "Financial Services",
	"STAR": "Financial Services",
	"TRIM": "Financial Services",
	"TUGU": "Financial Services",
	"WOMF": "Financial Services",

	// Consumer Goods (Non-Cyclicals)
	"AMRT": "Consumer Goods",
	"BACH": "Consumer Goods",
	"BAIK": "Consumer Goods",
	"BUDI": "Consumer Goods",
	"CMRY": "Consumer Goods",
	"CPIN": "Consumer Goods",
	"CSMI": "Consumer Goods",
	"FAST": "Consumer Goods",
	"GGRM": "Consumer Goods",
	"GULA": "Consumer Goods",
	"HERO": "Consumer Goods",
	"HMSP": "Consumer Goods",
	"ICBP": "Consumer Goods",
	"INDF": "Consumer Goods",
	"JPFA": "Consumer Goods",
	"LSIP": "Consumer Goods",
	"MYOR": "Consumer Goods",
	"RLCO": "Consumer Goods",
	"SIMP": "Consumer Goods",
	"TAPG": "Consumer Goods",
	"TGUK": "Consumer Goods",
	"UNSP": "Consumer Goods",
	"UNVR": "Consumer Goods",

	// Consumer Cyclicals
	"ASII": "Consumer Cyclicals",
	"AUTO": "Consumer Cyclicals",
	"EAST": "Consumer Cyclicals",
	"FILM": "Consumer Cyclicals",
	"HRTA": "Consumer Cyclicals",
	"LPPF": "Consumer Cyclicals",
	"MAPI": "Consumer Cyclicals",
	"TMPO": "Consumer Cyclicals",
	"VKTR": "Consumer Cyclicals",

	// Infrastructure
	"ADHI": "Infrastructure",
	"DCII": "Infrastructure",
	"EXCL": "Infrastructure",
	"GIAA": "Infrastructure",
	"ISAT": "Infrastructure",
	"JSMR": "Infrastructure",
	"KJEN": "Infrastructure",
	"MBSS": "Infrastructure",
	"SMDR": "Infrastructure",
	"TLKM": "Infrastructure",
	"TOWR": "Infrastructure",
	"TRUK": "Infrastructure",
	"WIKA": "Infrastructure",
	"WSKT": "Infrastructure",

	// Technology
	"BELI": "Technology",
	"BUKA": "Technology",
	"EMTK": "Technology",
	"GOTO": "Technology",

	// Healthcare
	"HEAL": "Healthcare",
	"KAEF": "Healthcare",
	"KLBF": "Healthcare",
	"LABS": "Healthcare",
	"SIDO": "Healthcare",

	// Real Estate & Property
	"ADCP": "Real Estate",
	"BSDE": "Real Estate",
	"CTRA": "Real Estate",
	"DART": "Real Estate",
	"INPP": "Real Estate",
	"KOTA": "Real Estate",
	"KPIG": "Real Estate",
	"SMRA": "Real Estate",
	"SSIA": "Real Estate",
	"WINR": "Real Estate",

	// Industrials
	"BNBR": "Industrials",
	"UNTR": "Industrials",
}

// OfficialCompanyNameMap maps ticker symbols to their official full company names.
var OfficialCompanyNameMap = map[string]string{
	"AADI": "PT Adaro Andalan Indonesia Tbk",
	"ADCP": "PT Adhi Commuter Properti Tbk",
	"ADHI": "PT Adhi Karya (Persero) Tbk",
	"ADMF": "PT Adira Dinamika Multi Finance Tbk",
	"ADMR": "PT Adaro Minerals Indonesia Tbk",
	"ADRO": "PT Adaro Energy Indonesia Tbk",
	"AHAP": "PT Asuransi Harta Aman Pratama Tbk",
	"AKRA": "PT AKR Corporindo Tbk",
	"AMMN": "PT Amman Mineral Internasional Tbk",
	"AMRT": "PT Sumber Alfaria Trijaya Tbk",
	"ANTM": "PT Aneka Tambang Tbk",
	"ARCI": "PT Archi Indonesia Tbk",
	"ARTO": "PT Bank Jago Tbk",
	"ASII": "PT Astra International Tbk",
	"AUTO": "PT Astra Otoparts Tbk",
	"AVIA": "PT Avia Avian Tbk",
	"BACH": "PT Bach Multi Global Tbk",
	"BAIK": "PT Bersama Mencapai Puncak Tbk",
	"BAJA": "PT Saranacentral Bajatama Tbk",
	"BANK": "PT Bank Aladin Syariah Tbk",
	"BBCA": "PT Bank Central Asia Tbk",
	"BBHI": "PT Allo Bank Indonesia Tbk",
	"BBNI": "PT Bank Negara Indonesia (Persero) Tbk",
	"BBRI": "PT Bank Rakyat Indonesia (Persero) Tbk",
	"BBSI": "PT Krom Bank Indonesia Tbk",
	"BBTN": "PT Bank Tabungan Negara (Persero) Tbk",
	"BEKS": "PT Bank Pembangunan Daerah Banten Tbk",
	"BELI": "PT Global Digital Niaga Tbk",
	"BFIN": "PT BFI Finance Indonesia Tbk",
	"BJBR": "PT Bank Pembangunan Daerah Jawa Barat dan Banten Tbk",
	"BJTM": "PT Bank Pembangunan Daerah Jawa Timur Tbk",
	"BMAS": "PT Bank Kasikorn Indonesia Tbk",
	"BMRI": "PT Bank Mandiri (Persero) Tbk",
	"BNBR": "PT Bakrie & Brothers Tbk",
	"BNGA": "PT Bank CIMB Niaga Tbk",
	"BNII": "PT Bank Maybank Indonesia Tbk",
	"BREN": "PT Barito Renewables Energy Tbk",
	"BRIS": "PT Bank Syariah Indonesia Tbk",
	"BRMS": "PT Bumi Resources Minerals Tbk",
	"BRNA": "PT Berlina Tbk",
	"BRPT": "PT Barito Pacific Tbk",
	"BSDE": "PT Bumi Serpong Damai Tbk",
	"BUDI": "PT Budi Starch & Sweetener Tbk",
	"BUKA": "PT Bukalapak.com Tbk",
	"BUMI": "PT Bumi Resources Tbk",
	"CBRE": "PT Cakra Buana Energi Resources Tbk",
	"CMRY": "PT Cisarua Mountain Dairy Tbk",
	"COAL": "PT Black Diamond Resources Tbk",
	"CPIN": "PT Charoen Pokphand Indonesia Tbk",
	"CSMI": "PT Cipta Selera Murni Tbk",
	"CTRA": "PT Ciputra Development Tbk",
	"CUAN": "PT Petrindo Jaya Kreasi Tbk",
	"DART": "PT Duta Anggada Realty Tbk",
	"DCII": "PT DCI Indonesia Tbk",
	"DSSA": "PT Dian Swastatika Sentosa Tbk",
	"DWGL": "PT Dwi Guna Laksana Tbk",
	"EAST": "PT Eastparc Hotel Tbk",
	"EKAD": "PT Ekadharma International Tbk",
	"ELSA": "PT Elnusa Tbk",
	"EMAS": "PT Merdeka Gold Resources Tbk",
	"EMTK": "PT Elang Mahkota Teknologi Tbk",
	"ENRG": "PT Energi Mega Persada Tbk",
	"ESSA": "PT ESSA Industries Indonesia Tbk",
	"EXCL": "PT XL Axiata Tbk",
	"FAST": "PT Fast Food Indonesia Tbk",
	"FILM": "PT MD Entertainment Tbk",
	"GGRM": "PT Gudang Garam Tbk",
	"GIAA": "PT Garuda Indonesia (Persero) Tbk",
	"GOTO": "PT GoTo Gojek Tokopedia Tbk",
	"GULA": "PT Aman Agrindo Tbk",
	"HEAL": "PT Medikaloka Hermina Tbk",
	"HERO": "PT Hero Supermarket Tbk",
	"HMSP": "PT H.M. Sampoerna Tbk",
	"HRTA": "PT Hartadinata Abadi Tbk",
	"ICBP": "PT Indofood CBP Sukses Makmur Tbk",
	"IFSH": "PT Ifishdeco Tbk",
	"IMPC": "PT Impack Pratama Industri Tbk",
	"INCF": "PT Indo Komoditi Korpora Tbk",
	"INCO": "PT Vale Indonesia Tbk",
	"INDF": "PT Indofood Sukses Makmur Tbk",
	"INKP": "PT Indah Kiat Pulp & Paper Tbk",
	"INPP": "PT Indonesian Paradise Property Tbk",
	"ISAT": "PT Indosat Tbk",
	"ITMG": "PT Indo Tambangraya Megah Tbk",
	"JPFA": "PT Japfa Comfeed Indonesia Tbk",
	"JSMR": "PT Jasa Marga (Persero) Tbk",
	"KAEF": "PT Kimia Farma Tbk",
	"KJEN": "PT Krida Jaringan Nusantara Tbk",
	"KLBF": "PT Kalbe Farma Tbk",
	"KOTA": "PT DMS Propertindo Tbk",
	"KPIG": "PT MNC Tourism Indonesia Tbk",
	"KRAS": "PT Krakatau Steel (Persero) Tbk",
	"LABS": "PT UBC Medical Indonesia Tbk",
	"LPPF": "PT Matahari Department Store Tbk",
	"LSIP": "PT PP London Sumatra Indonesia Tbk",
	"MAPI": "PT Mitra Adiperkasa Tbk",
	"MBMA": "PT Merdeka Battery Materials Tbk",
	"MBSS": "PT Mitrabahtera Segara Sejati Tbk",
	"MDKA": "PT Merdeka Copper Gold Tbk",
	"MEDC": "PT Medco Energi Internasional Tbk",
	"MEGA": "PT Bank Mega Tbk",
	"MYOR": "PT Mayora Indah Tbk",
	"PGAS": "PT Perusahaan Gas Negara Tbk",
	"PGEO": "PT Pertamina Geothermal Energy Tbk",
	"PSAB": "PT J Resources Asia Pasifik Tbk",
	"PTBA": "PT Bukit Asam Tbk",
	"PTRO": "PT Petrosea Tbk",
	"RAJA": "PT Rukun Raharja Tbk",
	"RATU": "PT Raharja Energi Cepu Tbk",
	"RLCO": "PT Abadi Lestari Indonesia Tbk",
	"SIDO": "PT Industri Jamu dan Farmasi Sido Muncul Tbk",
	"SIMP": "PT Salim Ivomas Pratama Tbk",
	"SINI": "PT Singaraja Putra Tbk",
	"SMDR": "PT Samudera Indonesia Tbk",
	"SMGR": "PT Semen Indonesia (Persero) Tbk",
	"SMMA": "PT Sinar Mas Multiartha Tbk",
	"SMRA": "PT Summarecon Agung Tbk",
	"SSIA": "PT Surya Semesta Internusa Tbk",
	"STAR": "PT Buana Artha Anugerah Tbk",
	"SULI": "PT SLJ Global Tbk",
	"TAPG": "PT Triputra Agro Persada Tbk",
	"TCPI": "PT Transcoal Pacific Tbk",
	"TGUK": "PT Platinum Wahab Nusantara Tbk",
	"TINS": "PT Timah Tbk",
	"TLKM": "PT Telkom Indonesia (Persero) Tbk",
	"TMPO": "PT Tempo Inti Media Tbk",
	"TOWR": "PT Sarana Menara Nusantara Tbk",
	"TPIA": "PT Chandra Asri Pacific Tbk",
	"TPL":  "PT Toba Pulp Lestari Tbk",
	"TRIM": "PT Trimegah Sekuritas Indonesia Tbk",
	"TRUK": "PT Guna Timur Raya Tbk",
	"TUGU": "PT Asuransi Tugu Pratama Indonesia Tbk",
	"UNSP": "PT Bakrie Sumatera Plantations Tbk",
	"UNTR": "PT United Tractors Tbk",
	"UNVR": "PT Unilever Indonesia Tbk",
	"VKTR": "PT VKTR Teknologi Mobilitas Tbk",
	"WIKA": "PT Wijaya Karya (Persero) Tbk",
	"WINR": "PT Winner Nusantara Jaya Tbk",
	"WOMF": "PT WOM Finance Tbk",
	"WSKT": "PT Waskita Karya (Persero) Tbk",
	"WTON": "PT Wijaya Karya Beton Tbk",
	"YPAS": "PT Yanaprima Hastapersada Tbk",
}

// BlacklistMap contains symbols that are non-stock entities (exchanges, indices, foreign stocks, regulators, non-public companies).
var BlacklistMap = map[string]bool{
	"AMZN":  true,
	"INTC":  true,
	"GS":    true,
	"OJK":   true,
	"BEI":   true,
	"IDX":   true,
	"IHSG":  true,
	"KSEI":  true,
	"BI":    true,
	"PNM":   true,
	"TMMIN": true,
	"RANS":  true,
	"JECX":  true,
	"BAIS":  true,
	"KAI":   true,
}

// IsBlacklisted returns true if the symbol is a non-stock entity that should not be tagged.
func IsBlacklisted(symbol string) bool {
	sym := strings.ToUpper(strings.TrimSpace(symbol))
	return BlacklistMap[sym]
}

// NormalizeSector returns the official IDX sector if known, or normalizes the provided tag.
func NormalizeSector(symbol string, tagSector string) string {
	sym := strings.ToUpper(strings.TrimSpace(symbol))
	if official, ok := OfficialIDXMap[sym]; ok {
		return official
	}

	tag := strings.TrimSpace(tagSector)
	if tag == "" || strings.EqualFold(tag, "Finansial") || strings.EqualFold(tag, "Financial Services") || strings.EqualFold(tag, "Financial") || strings.EqualFold(tag, "Perbankan") {
		return "Financial Services"
	}

	return tag
}

// GetOfficialCompanyName returns the official full name if known.
func GetOfficialCompanyName(symbol string, defaultName string) string {
	sym := strings.ToUpper(strings.TrimSpace(symbol))
	if official, ok := OfficialCompanyNameMap[sym]; ok {
		return official
	}
	return defaultName
}
