CREATE TABLE IF NOT EXISTS stock_profiles (
    symbol              VARCHAR(10) PRIMARY KEY REFERENCES stocks(symbol),
    description         TEXT,
    industry            VARCHAR(100),
    founded_year        INTEGER,
    city                VARCHAR(100),
    country             VARCHAR(50),
    employees           INTEGER,
    website             VARCHAR(255),
    market_cap          BIGINT,
    shares_outstanding  BIGINT,
    float_shares        BIGINT,
    trailing_pe         NUMERIC(10,2),
    price_to_book       NUMERIC(10,2),
    trailing_eps        NUMERIC(10,2),
    dividend_yield      NUMERIC(6,4),
    week_52_high        NUMERIC(12,2),
    week_52_low         NUMERIC(12,2),
    total_revenue       BIGINT,
    net_income          BIGINT,
    total_debt          BIGINT,
    total_assets        BIGINT,
    return_on_equity    NUMERIC(8,4),
    debt_to_equity      NUMERIC(8,2),
    fetched_at          TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);
